### ISSUE TITLE
String arguments that contain dashes do not parse properly

### ISSUE THREAD

**Issue by andyburke** [yargs/yargs-parser#145]
Eg:

```
foo -a 'aaa' -b 'bbb' command "-- string with dashes in it --"
```

This will fall afoul of this case:

https://github.com/bcoe/yargs/blob/master/lib/parser.js#L103

I ran into this trying to encrypt a private ssh key using [cryptex](https://github.com/TechnologyAdvice/Cryptex).

**Comment by bcoe** [comment]
@tristanMatthias @masaeedu I've transferred this issue to yargs-parser, would happily accept a patch if anyone feels like take a stab at the problem 👍

**Comment by tristanMatthias** [comment]
@bcoe working on one now :)

**Comment by tristanMatthias** [comment]
Ok @bcoe, I've submitted a pull request with the fix. Please note the solution required a little workaround (detailed in the PR) in which I add an extra set of quotation marks (then remove them later in the parser). The reason for this is because previously the tokenizer would create an array with `[...'--flag', '-valueStartingWithDash']`, and there was no way to determine if `'-valueStartingWithDash'` were flags or a string value (hence the extra wrapping). Let me know what you think!

**Comment by masaeedu** [comment]
@bcoe I think the issue I'm having is a little different (maybe I need to open a different issue). When you pass something like the following: `node foo.js --hey "-what -is -going -on"`, this will be parsed by the shell into `['node', 'foo.js', '--hey', '-what -is -going -on']` and then passed into node. When yargs looks at this list, it should interpret the array element after `--hey` as a positional argument instead of as a flag, because it is meaningless as a flag. I think if the regexen in the parser were anchored to the end they wouldn't accept `-what -is -going -on` as a valid flag, and so it would be treated positional argument as desired.

As far as escaping quotes goes, we can double up quotes so they survive the shell's expansion process and make it into node's `argv`.

**Comment by bcoe** [comment]
@masaeedu aha! I'd missed this edge-case, interesting.

@tristanMatthias thanks for a first pass at the solution, I wonder if we can figure out a way to avoid the temporary addition of quotes? working in the parser feels like a tech interview question doesn't it?

**Comment by tristanMatthias** [comment]
It does indeed! Is there a way we can definitively differentiate between them with the quotes stripped? I thought about holding something in memory, but that doesn't work when it's passed from the Tokenizer to the Parser

**Comment by masaeedu** [comment]
@bcoe btw, it isn't the operating system that's stripping quotes; it will faithfully forward whatever gets passed into `execvp` (or whatever syscall was actually used to create the child process). The problem is our shells work with string command lines, but the system call for creating a new process requires an array of strings. So each shell has its own quirky way of tokenizing whatever string you type into it into a argument list, which it then uses to make the syscall. The syscall just forwards this information faithfully.

This gets even hairier on Windows where things are precisely backwards; the system call for creating a new process expects a string instead of a list of arguments, so a shell like `Powershell` or `cmd` or whatever will first take the string you passed into it, do some substitutions and expansions and whatnot, and then prepare a string to pass into the system call for creating a new process. The system call will provide Node with a big string, which then *Node* will parse (only only Windows), into an `argv` which is what we see when we `console.log(process.argv)`.

I'm just braindumping all this stuff i've learned about the surprisingly convoluted world of command line parameters that I've learnt over the past couple of weeks, this may already have been common knowledge for you and @tristanMatthias.

**Comment by masaeedu** [comment]
The relevance of this stuff is that it's probably going to be pretty complicated to guess at what the original string and its quote wrapping was, because every shell can parse the string into an argv differently; whatever we get in the argv should be treated as the "source of truth". If a shell is stripping quotes before they ever make it into Node's argv, that should be avoided by using the shell's own rules for escaping and doubling up quotes.

**Comment by tristanMatthias** [comment]
Sounds like this should be the final answer to me. I agree with @masaeedu. For us to escape these issues, we can also use the `=` too! EG: `cli --foo="-bar"`

**Comment by bcoe** [comment]
@andyburke @masaeedu @tristanMatthias please try:

`+ yargs-parser@12.0.0`

I think it solves a bunch of issues around quotes and dashes in strings \o/ 

@tristanMatthias thanks for helping with the initial work, it got us going in the right direction.
