### ISSUE TITLE
Snyk show vulnerability in yargs-parser@5.0.0

### ISSUE THREAD

**Issue by yenanandu** [yargs/yargs-parser#264]
yargs-parser@5.0.0 is used in  yargs@7.1.0 which shows snyk error, Can you please check and fix it?

**Comment by bcoe** [comment]
👋 I won't be patching as far back as yargs@7 (this was released three years ago).

There is a fix in yargs@13, yargs@14, and yargs@15 however 🎉 If possible, I recommend using the latest and greatest version of yargs.

**Comment by evilebottnawi** [comment]
@bcoe can we do fix for yargs@12? A lot of dependencies still use old version

**Comment by ehmicky** [comment]
To give this a little more context: my problem is that the latest `gulp-cli` is using `yargs@7`, which depends on `yargs-parser@5`. The reason they cannot upgrade is because they support Node `0.10`.

They mention it in https://github.com/gulpjs/gulp/issues/2438, https://github.com/gulpjs/gulp-cli/issues/202, https://github.com/gulpjs/gulp-cli/issues/205, https://github.com/gulpjs/gulp-cli/issues/194, https://github.com/gulpjs/gulp-cli/issues/207.

I previously [expressed](https://github.com/gulpjs/glob-watcher/pull/41#issuecomment-488253999) some [concerns](https://twitter.com/ehmicky/status/1128982659030487042) that keeping Node `0.10` compatibility in Gulp would create such issues at some point.

That being said, I do understand that this is not Yargs fault and you should not have to do very old backports due to their odd Node.js compatibility policy.
